# Generated by Django 4.2 on 2023-05-07 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی محصولات',
                'verbose_name_plural': 'دسته بندی محصولات',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='درباره')),
                ('thumbnail', models.ImageField(upload_to='product/%y/%m/%d', verbose_name='تصویر')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('status', models.CharField(choices=[('available', 'موجود'), ('unavailable', 'ناموجود')], max_length=20, verbose_name='وضعیت')),
                ('specifications', models.TextField(verbose_name='مشخصات فنی')),
                ('discount', models.IntegerField(default=None, verbose_name='تخفیف')),
                ('number', models.IntegerField(verbose_name='تعداد')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییرات')),
                ('category', models.ManyToManyField(to='managers.productcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='managers.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.products', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مورد سفارش',
                'verbose_name_plural': 'موارد سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Send', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='درباره')),
                ('thumbnail', models.ImageField(upload_to='article/%y/%m/%d', verbose_name='تصویر')),
                ('status', models.CharField(choices=[('published', 'منتشر شده'), ('draft', 'پیش نویس')], max_length=10, verbose_name='وضعیت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییرات')),
                ('auther', models.ForeignKey(default=users.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
