# Generated by Django 4.2 on 2023-05-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
